package com.librarymgmnt.lms.security;

public class SecurityConstants {

	public static final long JWT_EXPIRE = 7000000;
	public static final String JWT_SECRET_KEY = "dfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbndfdgdfgkjfljhggflkbjhnfhfgbn";
	
}
